### PR TITLE
super washing machines code added

### PR DESCRIPTION
**Pull request by arjunpndt**
Description: 
- This code provides a method to calculate the minimum moves needed to balance the distribution of dresses in a set of washing machines.
- Efficiently balancing washing machines is crucial for optimizing laundry processes, and this code provides a practical solution.

Changes Made:

- Added a Java class `WashingMachine` containing a method `minMovesToBalance` which calculates the minimum moves required to balance the distribution of dresses in a set of washing machines.
- The `minMovesToBalance` method iterates through the array of machines, calculates the total number of dresses, and then determines the target number of dresses per machine. It then calculates the maximum imbalance among the machines.

Testing Done:
- I conducted several test cases, including cases with unevenly distributed dresses and cases with evenly distributed dresses. Additionally, I tested edge cases with a small number of machines to ensure accuracy.

Additional Notes: 
- This contribution aims to enhance the efficiency of laundry processes, which is a fundamental aspect of many industries. By making this code available, I hope to facilitate collaboration and innovation in this field during Hacktoberfest 2023.

Related Issue: This contribution addresses #67

### CODE REVIEW

**Comment by arjunpndt** [comment]
In this pull request, I've addressed issue #67 , which is related to the Super Washing Machines code contribution under the First Contribution folder. Please review and merge it.

**Comment by arjunpndt** [comment]
In this pull request, I've addressed issue #67  , which is related to the Super Washing Machines code contribution under the First Contribution folder. Please review and merge it.

**Comment by arjunpndt** [comment]
Issue #60 resolved

**Comment by arjunpndt** [comment]
Issue #67 resolved

**Comment by tangorishi** [comment]
@arjunpndt kindly use the pr template given in readme file

**Comment by arjunpndt** [comment]
> @arjunpndt kindly use the pr template given in readme file

I've updated the description in accordance with the PR template provided in the README file. Please proceed with the merge.

**Comment by tangorishi** [comment]
gg @arjunpndt

**Review by tangorishi — APPROVED** [review]

**Pull request merged**
