### PR TITLE
Created PalindromeChecker.java

### PR DESCRIPTION
**Pull request by Ankit-Saha08**
**Description:** 
As per issue ( #20 ), I have created and contributed a program named PalindromeChecker.java which checks the validity of a _Palindromic String_ . I have coded a easy, comprehensive, 100% tested solution in Java. This contribution will certainly add value to the repository as part of codebase enrichment.

**Changes Made:**
   * Created a File named PalindromeChecker.java
   * Provide a solution that implements few more simple concepts of Java programming - 
      1. Taking user input through Scanner class.
      2. Coded using user-defined function isPalin(String s) for better readability. 3. Used the concept of flag-variable for checking validity.

**Testing Done:**
The code contributed is absolutely for all possible scenarios. PFA few sample test-cases used for the same:
- [x] Test-Case 1: Input: wrd = Palindrome Output: Palindrome is not a Palindrome word
- [x] Test-Case 2: Input: wrd = Madam Output: Madam is a Palindrome word
- [x] Test-Case 3: Input: wrd = abcdcba efgfe Output: abcdcba is a Palindrome word Note: In this test case the word until white space is picked since the code was created for checking a word and not a sentence.

**Additional Notes:**
Hence, I have successfully contributed this code as part of my open-source contribution journey during Hacktoberfest 2023. Hopefully, my contribution will be a good learning for newbies in Java programming. Looking forward to getting my contribution merged which will definitely enrich the repository by fulfilling its agenda and also serve to be a great motivation for me.

### CODE REVIEW

**Comment by Ankit-Saha08** [comment]
I request the maintainer @tangorishi to kindly review and accept my contribution with "hacktoberfest-accepted" label.

**Comment by Ankit-Saha08** [comment]
@tangorishi Please merge my PR with "hacktoberfest-accepted" label

**Review by tangorishi — APPROVED** [review]

**Comment by tangorishi** [comment]
GG @Ankit-Saha08

**Comment by Moulali2004** [comment]
tangorishi could you please assign me this issue

**Pull request merged**
