### PR TITLE
Add some number identifying programs

### LINKED ISSUE #73: Add Number Identification Problems
Add Programs to identify these numbers:-
- Armstrong number
- Palindrome number
- Prime number
- Krishnamurthy number
- Happy number
- Automorphic number
- Kaprekar number
- Unique number
- Pronic number

### PR DESCRIPTION
**Pull request by itsyourap**
**Description:** This PR will add some basic number related identification problems. (closes #73)

**Changes Made:**
Added some number identifying programs
- Armstrong number
- Palindrome number
- Prime number
- Krishnamurthy number
- Happy number
- Automorphic number
- Kaprekar number
- Unique number
- Pronic number

**Testing Done:**
- Armstrong number
    - 153 -> true
    - 123 -> false
- Palindrome number
    - 1221 -> true
    - 1732 -> false
- Prime number
    - 17 -> true
    - 12 -> false
- Krishnamurthy number
    - 145 -> true
    - 122 -> false
- Happy number
    - 19 -> true
    - 12 -> false
- Automorphic number
    - 25 -> true
    - 12 -> false
- Kaprekar number
    - 45 -> true
    - 32 -> false
- Unique number
    - 1234 -> true
    - 1223 -> false
- Pronic number
    - 56 -> true
    - 13 -> false

**Additional Notes:** These are some basic number programs which will help the newcomers in the world of programming.

---

By submitting this PR, I confirm that my contributions are made under the terms of the [MIT License](LICENSE).

Kindly merge this PR

### CODE REVIEW

**Comment by tangorishi** [comment]
kindly use the pr template given in the readme.md file also create an issue for the same and get it assigned to yourself

**Comment by itsyourap** [comment]
> kindly use the pr template given in the readme.md file also create an issue for the same and get it assigned to yourself

Sorry for the oversight. Fixed now

**Comment by tangorishi** [comment]
@itsyourap kindly store all these codes in a separate  folder inside FirstContribution folder.

**Comment by itsyourap** [comment]
> @itsyourap kindly store all these codes in a separate folder inside FirstContribution folder.

Yes. All of them are stored in a folder named "Numbers" inside the "FirstContribution" folder

**Review by tangorishi — APPROVED** [review]

**Comment by tangorishi** [comment]
Good Work @itsyourap kudos for merging your pr under hacktoberfest 2023.

**Comment by itsyourap** [comment]
Thanks a lot @tangorishi ❤️🙌

**Pull request merged**
