### PR TITLE
Create FizzBuzz.java

### PR DESCRIPTION
**Pull request by Ankit-Saha08**
**Description:** 
As per issue ( #10 ), I have created and contributed a program named FizzBuzz.java which accomplishes all the functionalities of the _FizzBuzz_ problem. I have coded a easy, comprehensive, 100% tested solution in Java. This contribution will certainly add value to the repository as part of codebase enrichment.

**Changes Made:**
   * Created a File named FizzBuzz.java
   * Provide a solution that implements few more simple concepts of Java programming - 
      1. Taking user input through Scanner class.
      2. Coded using user-defined function fizzBuss(int n) for better readibility.
      3. Implemented the solution for FizzBuzz using Java Collection Framework approach that uses
          ArrayList to demonstrate the concept of dynamic memory allocation.

**Testing Done:**
The code contributed is absolutely for all possible scenarios. PFA few sample test-cases used for the same:
- [x] Test-Case 1:
        Input: n = 3
        Output: ["1","2","Fizz"]
- [x] Test-Case 2:
        Input: n = 5
        Output: ["1","2","Fizz","4","Buzz"]
- [x] Test-Case 3:
        Input: n = 15
        Output: ["1","2","Fizz","4","Buzz","Fizz","7","8","Fizz","Buzz","11","Fizz","13","14","FizzBuzz"]

**Additional Notes:**
Hence, I have successfully contributed this code as part of my open-source contribution journey during Hacktoberfest 2023. As a beginner in open-source, I found contributing, initially, to codebase repositories like this would be a great learning for me to go ahead. Looking forward to getting my contribution merged which will definitely enrich the repository by fulfilling its agenda and also serve to be a great motivation for me.

### CODE REVIEW

**Comment by Ankit-Saha08** [comment]
* I request the maintainer (@tangorishi) to kindly review and merge the solution to the issue - #10.
* Also, I beseech the maintainer to kindly add "hacktoberfest-accepted" label to my PR #15.

**Comment by tangorishi** [comment]
Kindly use [PR Template](https://github.com/tangorishi/learnJava#hacktoberfest-2023-contribution-pull-request-template-message) to write the PR message before requesting for a merge request. 🍉

**Comment by Ankit-Saha08** [comment]
@tangorishi  Kindly check the PR message which I have updated as per PR Template. Now I request to merge my PR #15 with "hacktoberfest-accepted" label as a part of Hacktoberfest 2023 journey. Thank you!!

**Review by tangorishi — APPROVED** [review]

**Comment by tangorishi** [comment]
🎉 Thanks for your contribution! Your PR has been successfully merged.

**Pull request merged**
