### PR TITLE
Create common_prefix.java

### PR DESCRIPTION
**Pull request by Dinki-Yaduwanshi**
Write a function to find the longest common prefix string amongst an array of strings.If there is no common prefix, return an empty string "".

### CODE REVIEW

**Comment by tangorishi** [comment]
@Dinki-Yaduwanshi kindly create an issue for the same and get it assigned then use the pr template provided in readme.md

**Comment by Dinki-Yaduwanshi** [comment]
Okay, I have created the issue as you told me and will resubmit the PR in the correct format. Thank you!

**Comment by tangorishi** [comment]
use proper pr template given in readme file [this](https://github.com/tangorishi/learnJava#hacktoberfest-2023-contribution-pull-request-template-message)

**Comment by tangorishi** [comment]
updates ? @Dinki-Yaduwanshi

**Pull request closed without merging**
