### PR TITLE
Add Java code examples for Sorting Algorithm

### PR DESCRIPTION
**Pull request by Janani-Balasooriya**
I am thrilled to contribute to this repository by implementing three essential sorting algorithms: Bubble Sort, Selection Sort, and Merge Sort. This contribution aims to enhance the repository's capabilities by adding fundamental sorting algorithms that can be used as references or as part of various projects. Sorting algorithms are fundamental in computer science, and providing multiple sorting options can be highly valuable.

Changes Made:
- Added the BubbleSort class containing a bubbleSort method to sort an integer array using the Bubble Sort algorithm.
- Created two test cases to demonstrate the correctness of the bubbleSort method.
- Implemented a printArray utility method for displaying sorted arrays neatly.
- Added the SelectionSort class containing a selectionSort method to sort an integer array using the Selection Sort algorithm.
- Created two test cases to demonstrate the correctness of the selectionSort method.
- Implemented a printArray utility method for displaying sorted arrays neatly.
- Added the MergeSort class containing a mergeSort method to sort an integer array using the Merge Sort algorithm.
- Created two test cases to demonstrate the correctness of the mergeSort method.
- Implemented a printArray utility method for displaying sorted arrays neatly.

Technical Details:
- The Bubble Sort algorithm (bubbleSort method) sorts an integer array in ascending order by repeatedly comparing and swapping adjacent elements. Its time complexity is O(n^2), making it suitable for small to moderately sized arrays.
- The Selection Sort algorithm (selectionSort method) sorts an integer array in ascending order by selecting the minimum element in the unsorted portion and moving it to the sorted portion. It also has a time complexity of O(n^2).
- The Merge Sort algorithm (mergeSort method) sorts an integer array by recursively splitting it into halves, sorting them, and then merging them back together. It offers a time complexity of O(n log n), making it efficient for larger datasets.

Testing Done:
I conducted thorough testing to ensure the correctness of all three sorting algorithms:
- For each algorithm, I provided two test cases:
    - Test Case 1: A small array containing {64, 34, 25, 12, 22, 11, 90}.
    - Test Case 2: A larger array containing {5, 2, 9, 1, 5, 6, 0, 3, 8, 7, 4}.
All test cases produced the expected results, and the sorted arrays were displayed correctly.

Additional Notes:
This contribution aligns perfectly with the goals of Hacktoberfest 2023 by adding valuable algorithmic implementations to the repository. Sorting algorithms are fundamental building blocks in computer science, and this collection of sorting methods can serve as an excellent resource for developers looking to understand sorting algorithms or as part of projects requiring sorting functionality.

I eagerly await your feedback and suggestions to further enhance these contributions. Thank you for considering my pull request.

Happy Hacking!
Janani Balasooriya

### CODE REVIEW

**Comment by Janani-Balasooriya** [comment]
I request @tangorishi  to kindly check my contribution related to the issue #11 and accept my contribution with "hacktoberfest-accepted" label.
Thank you!!

**Comment by tangorishi** [comment]
Hi @Janani-Balasooriya you are always welcomed to open an issue and get it assigned to yourself so as to maintain a flow of the project keeping in mind the guidelines of **HacktoberFest** therefore you need to open this as new issue and get assigned to yourself or if this issue is already opened you can get it assigned it to yourself.

**Comment by Janani-Balasooriya** [comment]
Thank you so much for replying. I just noticed someone has assigned to that issue 2 minutes before I made the pull request. Can you create an issue regarding the Bubble Sort algorithm? I'm new to here and this is my first pull request. :)

**Comment by tangorishi** [comment]
Yes you can be assigned that issue too, a single issue can be assigned to upto 10 people you need to make a comment under that issue so that we can assign you that issue, then after you can start working on it

**Comment by Janani-Balasooriya** [comment]
Thank you! I commented under that issue. Could you please assign me as well?

**Comment by Janani-Balasooriya** [comment]
Hi @tangorishi Now, I'm assigned to issue #11 . Do I need to make another pull request or can you consider merging this? Could you please guide me? 
Thank you!

**Comment by Janani-Balasooriya** [comment]
Hi @tangorishi I have wrote the codes for bubble sort, selection sort and merge sort as mentioned in the issue #11 and stored them in a separate folder named "Sorting". Could you please check my pull request?
Thank you!

**Comment by tangorishi** [comment]
@Janani-Balasooriya you need to make SORTING folder inside the 16_FirstContribution folder

**Comment by Janani-Balasooriya** [comment]
I have created a folder SORTING inside the 16_FirstContribution folder and added the algorithm codes to it. Could you please recheck my contribution @tangorishi ?

Thank you! :)

**Comment by tangorishi** [comment]
@Janani-Balasooriya good work ! you have your hacktober fest pr merged.

**Review by tangorishi — APPROVED** [review]

**Pull request merged**
