### PR TITLE
Add java code examples for PasswordGenerator

### LINKED ISSUE #23: Random Password Generator in Java
Create a Java class that generates strong and random passwords with specified criteria (length, complexity, etc.).

### PR DESCRIPTION
**Pull request by SumitMangrati**
resolves #23 

Description:
I have added the working java code for Random Password Generator

Changes made:
This java code asks the user to input the length of the password they want and the complexity of their password. 
The complexity of the password is set in 3 parameters 
EASY(1) - includes only uppercase and lowercase characters
MEDIUM(2) - includes only uppercase lowercase and numbers
HARD(3)- includes uppercase, lowercase, numbers and special characters
I have used the random class for generation.
if the user inputs anything except for 1 2 3 then the program will return a blank string to denote the input is invalid

Testing done:
The following test case were run to check the correctness of the program.

Test Case 1: length as 14
                     complexity as 1
Test Case 2:  length as 25
                      complexity as 2
Test Case 3: length as 89
                     complexity as 3
Test Case 4: length as 6
                     complexity as 0
All the test cases produced the expected results, and the password was generated as per the user's input 

Additional Notes:
I have just started my journey on open source and I want to learn more about it. This repository matched my tech stack and through this repo I'll be able to learn more.

### CODE REVIEW

**Comment by tangorishi** [comment]
Code seems good and clear but you are advised to follow [this](https://github.com/tangorishi/learnJava#hacktoberfest-2023-contribution-pull-request-template-message) template while pushing your pull request.

**Comment by SumitMangrati** [comment]
@tangorishi  hey i have editing my pr description please check it and if anything doesn't matches the requirement please guide me through it.

**Comment by tangorishi** [comment]
@SumitMangrati  everything is almost good to go you just need to write down the test cases instead of providing a picture.

**Comment by SumitMangrati** [comment]
updated my PR description

**Comment by tangorishi** [comment]
Good work @SumitMangrati  you can add your profile picture as a contributor in the readme.md file

**Review by tangorishi — APPROVED** [review]

**Pull request merged**
