### PR TITLE
Neon Numbers Generator

### PR DESCRIPTION
**Pull request by its-your-invi**
# Hacktoberfest 2023 Contribution Pull Request

**Description:**
I've contributed the Java code for a Neon Numbers generator. This code allows users to find and display Neon numbers up to a specified limit.

**Changes Made:**
I've added the Java code for the Neon Numbers generator, including a `main` method to take user input and display Neon numbers up to the specified limit, and a `isNeonNumber` method to check if a number is a Neon number.

**Technical Details:**
The code provides functionality to calculate and display Neon numbers up to a user-specified limit. It follows the Neon number definition by checking if the sum of the squares of the digits of a number equals the original number.

**Testing Done:**
I've tested the code to ensure it functions correctly, including various input limits and scenarios. The code accurately identifies and displays Neon numbers.
image

**Additional Notes:**
This contribution adds a Neon Numbers generator to the repository, which can be valuable for educational purposes and for those interested in exploring Neon numbers. I hope this contribution aligns with the goals of Hacktoberfest 2023 and open source collaboration.

Thank you for considering my contribution. Your feedback is appreciated.

### CODE REVIEW

**Comment by its-your-invi** [comment]
Closed #18

**Comment by tangorishi** [comment]
@its-your-invi  kindly follow the PR template in the README.md file before creating pr, in order to maintain a common flow of the project along with the contributing guidelines it is necessary to follow the things.

**Comment by its-your-invi** [comment]
Hi @tangorishi,

I've revised the PR message, ensuring its correctness and elegance. Kindly review it and let me know if any further adjustments are needed. Additionally, please consider adding the `hacktober-accepted` label to the PR.

Thank you!

**Review by tangorishi — APPROVED** [review]

**Comment by tangorishi** [comment]
GG @its-your-invi

**Pull request merged**
